### ISSUE TITLE
Issue tab is missing liquid_progress_indicator_v2 repos

### ISSUE THREAD

**Issue by guyluz11** [Scintillam/fenles_plausible_analytics#1]
I have found [liquid_progress_indicator_v2](https://pub.dev/packages/liquid_progress_indicator_v2) package and the repo link linked to your repo https://github.com/Scintillam/liquid_progress_indicator_v2

Unfortunately the issue tab is missing and you need to add it in the repo settings.

![image](https://github.com/Scintillam/fenles_plausible_analytics/assets/9304740/7ed7bdae-bf43-49fd-b211-63c3fea3466f)

Can you please add it so that the development of the repo can continue?

It came to my understanding that the package does not work on flutter 3.22.1 and I am thinking of taking a look and I prefer not to do it to unmaintained repo.
Without the issue tab I can't ask if the repo is maintained.

Thanks in advance

**Comment by Pablo-Aldana** [comment]
Hi @guyluz11 ! 

Thanks a lot for letting us know! we completely missed. It has been already activate it. 

Please let me know if you can now see it.

Cheers!

**Comment by guyluz11** [comment]
I can see the issue tab now.

Thanks
